### ISSUE TITLE
normalize.css should be imported before foundation.min.css

### ISSUE THREAD

**Issue by caioalonso** [voltrb/volt-foundation#4]
What I currently get:

```
<link href="/assets/css/foundation.min.css" media="all" rel="stylesheet" type="text/css" />
<link href="/assets/css/normalize.css" media="all" rel="stylesheet" type="text/css" />
```

**Comment by danReynolds** [comment]
Thanks, I looked at https://github.com/voltrb/volt-bootstrap/blob/master/app/bootstrap/assets/css/01-bootstrap.css and it appears that they just include normalize at the top of the file instead so I switched to that.
